[build]
  publish = "build/web"
  command = "flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=FLAVOR=production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
