providers = ["python"]

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install --no-cache-dir -r backend/requirements.txt"
]

[start]
cmd = "gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --log-level debug"
