// lib/services/per_page_illustration_prefetcher.dart
//
// Spike: when a BYOK user reads a story, generate one Imagen illustration
// per page in the background. The reader almost always spends longer on a
// page than Imagen takes to return (~5–10s vs 30–60s of read-aloud time),
// so a serial worker that prefers the page after the user's current
// position keeps every page illustrated by the time they swipe.
//
// Each page exposes a [ValueListenable] of [PageIllustrationState] so the
// UI can render either bytes, a skeleton, or nothing. Generated bytes are
// persisted to <docs>/illustrations/<storyId>/page_<n>.png so re-opens are
// instant and a re-read costs zero quota.

import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';

import '../config/environment.dart';
import 'api_service_manager.dart';

enum PageIllustrationStatus { idle, queued, loading, ready, failed, quotaExceeded }

@immutable
class PageIllustrationState {
  const PageIllustrationState({
    required this.status,
    this.bytes,
    this.error,
  });

  final PageIllustrationStatus status;
  final Uint8List? bytes;
  final String? error;

  static const idle = PageIllustrationState(status: PageIllustrationStatus.idle);

  PageIllustrationState copyWith({
    PageIllustrationStatus? status,
    Uint8List? bytes,
    String? error,
  }) =>
      PageIllustrationState(
        status: status ?? this.status,
        bytes: bytes ?? this.bytes,
        error: error ?? this.error,
      );
}

class PerPageIllustrationPrefetcher {
  PerPageIllustrationPrefetcher({
    required this.storyId,
    required this.pageTexts,
    required this.characterName,
    required this.age,
    this.theme,
    this.style = "children's book",
    this.therapeuticFocus,
    this.characterAppearance,
    this.companions,
    this.sceneRequirements,
    this.heroPower,
    this.allowServerKey = false,
    Set<int>? skipPages,
    http.Client? client,
  })  : _skipPages = Set<int>.from(skipPages ?? const <int>{}),
        _client = client ?? http.Client(),
        _states = List.generate(
          pageTexts.length,
          (_) => ValueNotifier<PageIllustrationState>(PageIllustrationState.idle),
        );

  final String storyId;
  final List<String> pageTexts;
  final String characterName;
  final int age;
  final String? theme;
  final String style;
  final String? therapeuticFocus;
  final Map<String, dynamic>? characterAppearance;
  final List<Map<String, String>>? companions;
  final String? sceneRequirements;
  /// Superhero power id (e.g. `feeling_sense`, `soft_step`). When present the
  /// backend may apply a per-power visual signature override. Null for
  /// non-superhero stories or bands without a power picker.
  final String? heroPower;
  /// When true, fall through to the backend's server-managed Imagen key when
  /// the user has no BYOK token. The backend's `/generate-illustrations`
  /// route already supports both paths — it uses `user_api_key` if present,
  /// otherwise the server's image generator. Used for Sprout-band reads
  /// where per-page art is essential and we don't want to gate it on BYOK.
  final bool allowServerKey;

  final Set<int> _skipPages;
  final http.Client _client;
  final List<ValueNotifier<PageIllustrationState>> _states;
  final Queue<int> _queue = Queue<int>();
  final Set<int> _enqueued = <int>{};

  bool _running = false;
  bool _disposed = false;
  String? _userApiKey;

  /// Latest quota usage reported by the backend (`quota_used`/`quota_limit`).
  /// Null when no metered response has come back yet, or when BYOK is in use
  /// (BYOK responses don't carry quota numbers).
  int? _quotaUsed;
  int? _quotaLimit;
  final ValueNotifier<bool> _quotaExceeded = ValueNotifier<bool>(false);

  /// Consecutive non-quota failures. Once this hits [_failureCircuitBreaker]
  /// we stop firing requests and mark every remaining page as failed — both
  /// to save round-trips and to stop the loading-skeleton flicker on each
  /// page when generation can't possibly succeed (revoked BYOK key, server
  /// Imagen quota exhausted, OpenRouter down, etc).
  int _consecutiveFailures = 0;
  static const int _failureCircuitBreaker = 2;

  /// True once any page in this story has come back with
  /// `code: ILLUSTRATION_QUOTA_EXCEEDED`. Subsequent fetches short-circuit.
  bool get hasQuotaExceeded => _quotaExceeded.value;

  /// Listenable form of [hasQuotaExceeded] so screens can rebuild banners
  /// when the cap is hit mid-story.
  ValueListenable<bool> get quotaExceededListenable => _quotaExceeded;

  int? get quotaUsed => _quotaUsed;
  int? get quotaLimit => _quotaLimit;

  ValueListenable<PageIllustrationState> stateOf(int pageIndex) {
    if (pageIndex < 0 || pageIndex >= _states.length) {
      return ValueNotifier<PageIllustrationState>(PageIllustrationState.idle);
    }
    return _states[pageIndex];
  }

  /// Load any previously persisted images and queue the rest in reading order.
  Future<void> initialize() async {
    if (_disposed) return;

    _userApiKey = await ApiServiceManager.getUserApiKey();
    final keyLen = _userApiKey?.length ?? 0;
    debugPrint(
      'PerPagePrefetcher: BYOK key ${keyLen > 0 ? "present (len=$keyLen)" : "ABSENT"}; '
      'allowServerKey=$allowServerKey; pages=${pageTexts.length}',
    );
    if ((_userApiKey == null || _userApiKey!.isEmpty) && !allowServerKey) {
      // BYOK not configured and server-key path not enabled — leave every
      // page idle.
      return;
    }

    final dir = await _illustrationsDir();
    for (int i = 0; i < pageTexts.length; i++) {
      if (_skipPages.contains(i)) continue;
      if (dir != null) {
        final file = File('${dir.path}/page_$i.png');
        if (await file.exists()) {
          try {
            final bytes = await file.readAsBytes();
            _states[i].value = PageIllustrationState(
              status: PageIllustrationStatus.ready,
              bytes: bytes,
            );
            continue;
          } catch (_) {
            // Corrupt file — fall through to regenerate.
          }
        }
      }
      _enqueue(i);
    }
    unawaited(_drain());
  }

  /// Bump [pageIndex] (and the next one) toward the front of the queue so
  /// the reader's upcoming pages are generated first.
  void prioritize(int pageIndex) {
    if (_disposed) return;
    for (final idx in [pageIndex, pageIndex + 1]) {
      if (idx < 0 || idx >= pageTexts.length) continue;
      if (_skipPages.contains(idx)) continue;
      final state = _states[idx].value;
      if (state.status == PageIllustrationStatus.ready ||
          state.status == PageIllustrationStatus.loading) {
        continue;
      }
      _queue.remove(idx);
      _queue.addFirst(idx);
      _enqueued.add(idx);
      _states[idx].value =
          const PageIllustrationState(status: PageIllustrationStatus.queued);
    }
    unawaited(_drain());
  }

  void _enqueue(int pageIndex) {
    if (_enqueued.contains(pageIndex)) return;
    _enqueued.add(pageIndex);
    _queue.addLast(pageIndex);
    _states[pageIndex].value =
        const PageIllustrationState(status: PageIllustrationStatus.queued);
  }

  Future<void> _drain() async {
    if (_running || _disposed) return;
    _running = true;
    try {
      while (_queue.isNotEmpty && !_disposed) {
        // Once the monthly free-tier cap is hit, every subsequent
        // /generate-illustrations call returns the same error — short-circuit
        // locally so we don't burn round-trips for the rest of the story.
        if (_quotaExceeded.value) {
          while (_queue.isNotEmpty) {
            final idx = _queue.removeFirst();
            _enqueued.remove(idx);
            _markPageQuotaExceeded(idx);
          }
          break;
        }
        // Generic failure circuit breaker. Stops the loading-skeleton flicker
        // on every page when illustration generation is hopeless this session.
        if (_consecutiveFailures >= _failureCircuitBreaker) {
          while (_queue.isNotEmpty) {
            final idx = _queue.removeFirst();
            _enqueued.remove(idx);
            _states[idx].value = const PageIllustrationState(
              status: PageIllustrationStatus.failed,
              error: 'circuit-breaker',
            );
          }
          break;
        }
        final pageIndex = _queue.removeFirst();
        _enqueued.remove(pageIndex);
        await _generatePage(pageIndex);
        // Light throttle — matches existing batch generator's pacing.
        await Future<void>.delayed(const Duration(milliseconds: 250));
      }
    } finally {
      _running = false;
    }
  }

  void _markPageQuotaExceeded(int pageIndex) {
    if (pageIndex < 0 || pageIndex >= _states.length) return;
    _states[pageIndex].value =
        const PageIllustrationState(status: PageIllustrationStatus.quotaExceeded);
  }

  Future<void> _generatePage(int pageIndex) async {
    if (_disposed) return;
    if (_quotaExceeded.value) {
      _markPageQuotaExceeded(pageIndex);
      return;
    }
    final apiKey = _userApiKey;
    final hasUserKey = apiKey != null && apiKey.isNotEmpty;
    if (!hasUserKey && !allowServerKey) return;

    _states[pageIndex].value =
        const PageIllustrationState(status: PageIllustrationStatus.loading);

    try {
      final scene = _sceneFromPage(pageTexts[pageIndex]);
      final headers = await ApiServiceManager.authHeaders();
      // Backend `/generate-illustrations` uses user_api_key when present and
      // otherwise falls back to the server's image generator, so we only
      // include the key when we actually have one.
      final response = await _client
          .post(
            Uri.parse('${Environment.backendUrl}/generate-illustrations'),
            headers: headers,
            body: jsonEncode({
              'scene_description': scene,
              'character_name': characterName,
              'style': style,
              'num_images': 1,
              'age': age,
              if (therapeuticFocus != null) 'therapeutic_focus': therapeuticFocus,
              if (characterAppearance != null)
                'character_appearance': characterAppearance,
              if (companions != null && companions!.isNotEmpty)
                'companions': companions,
              if (heroPower != null && heroPower!.isNotEmpty)
                'power_id': heroPower,
              if (hasUserKey) 'user_api_key': apiKey,
            }),
          )
          .timeout(const Duration(seconds: 60));

      if (_disposed) return;

      if (response.statusCode != 200) {
        _consecutiveFailures++;
        _states[pageIndex].value = PageIllustrationState(
          status: PageIllustrationStatus.failed,
          error: 'HTTP ${response.statusCode}',
        );
        return;
      }

      final data = jsonDecode(response.body) as Map<String, dynamic>;

      // Capture quota numbers when present (backend includes them on both
      // success and the quota-exceeded path; BYOK responses omit them).
      final quotaUsed = data['quota_used'];
      final quotaLimit = data['quota_limit'];
      if (quotaUsed is int) _quotaUsed = quotaUsed;
      if (quotaLimit is int) _quotaLimit = quotaLimit;

      // Free-tier monthly cap hit. Backend always returns code:
      // ILLUSTRATION_QUOTA_EXCEEDED for this case — distinct from the
      // transient-failure path (which has no code but also an empty list).
      if (data['code'] == 'ILLUSTRATION_QUOTA_EXCEEDED') {
        _quotaExceeded.value = true;
        _markPageQuotaExceeded(pageIndex);
        return;
      }

      final illustrations = (data['illustrations'] as List?) ?? const [];
      if (illustrations.isEmpty) {
        _consecutiveFailures++;
        _states[pageIndex].value = const PageIllustrationState(
          status: PageIllustrationStatus.failed,
          error: 'empty response',
        );
        return;
      }

      final first = illustrations.first as Map<String, dynamic>;
      final imageData = first['image_data'] as String?;
      if (imageData == null || imageData.isEmpty) {
        _consecutiveFailures++;
        _states[pageIndex].value = const PageIllustrationState(
          status: PageIllustrationStatus.failed,
          error: 'missing image_data',
        );
        return;
      }

      final raw = imageData.contains(',') ? imageData.split(',').last : imageData;
      final bytes = base64Decode(raw);

      // Persist before exposing — failures fall through to ephemeral display.
      try {
        final dir = await _illustrationsDir();
        if (dir != null) {
          final file = File('${dir.path}/page_$pageIndex.png');
          await file.writeAsBytes(bytes, flush: true);
        }
      } catch (e) {
        debugPrint('PerPagePrefetcher: persist failed for page $pageIndex: $e');
      }

      if (_disposed) return;
      _consecutiveFailures = 0;
      _states[pageIndex].value = PageIllustrationState(
        status: PageIllustrationStatus.ready,
        bytes: bytes,
      );
    } catch (e) {
      if (_disposed) return;
      _consecutiveFailures++;
      _states[pageIndex].value = PageIllustrationState(
        status: PageIllustrationStatus.failed,
        error: e.toString(),
      );
    }
  }

  String _sceneFromPage(String pageText) {
    final trimmed = pageText.trim();
    final scene =
        trimmed.length > 600 ? '${trimmed.substring(0, 600)}…' : trimmed;
    final reqs = sceneRequirements?.trim() ?? '';
    if (reqs.isEmpty) return scene;
    return '$scene\n\nStory elements to visibly include: $reqs';
  }

  Future<Directory?> _illustrationsDir() async {
    if (kIsWeb) return null;
    try {
      final docs = await getApplicationDocumentsDirectory();
      final dir = Directory('${docs.path}/illustrations/$storyId');
      if (!await dir.exists()) {
        await dir.create(recursive: true);
      }
      return dir;
    } catch (e) {
      debugPrint('PerPagePrefetcher: illustrations dir unavailable: $e');
      return null;
    }
  }

  void dispose() {
    _disposed = true;
    _queue.clear();
    _enqueued.clear();
    for (final notifier in _states) {
      notifier.dispose();
    }
    _quotaExceeded.dispose();
    _client.close();
  }
}
