import 'package:flutter/material.dart';

/// A small, tasteful "Created with AI" badge.
///
/// Used to label AI-generated content (stories, illustrations, avatars) in a
/// child-app-appropriate way. Google Play's Generative-AI policy, Apple's
/// review guidelines, and EU AI Act Art. 50 all require AI-generated output to
/// be disclosed in-app — this badge is the persistent, visible disclosure.
///
/// Two presentations:
///  - default chip: a pill with an icon + label, for placing under content.
///  - [AiGeneratedBadge.corner]: a compact pill sized to overlay the corner of
///    an image (avatar / illustration).
class AiGeneratedBadge extends StatelessWidget {
  /// Label text. Defaults to a friendly, plain-language phrase.
  final String label;

  /// When true, renders the compact corner-overlay variant.
  final bool compact;

  /// Base color of the badge. Defaults to a translucent dark pill that reads
  /// on both light and dark/illustrated backgrounds.
  final Color? background;

  /// Foreground (icon + text) color.
  final Color foreground;

  const AiGeneratedBadge({
    super.key,
    this.label = 'Created with AI',
    this.compact = false,
    this.background,
    this.foreground = Colors.white,
  });

  /// Compact variant intended to sit in the corner of an AI-generated image
  /// (avatar or illustration). Use inside a [Stack] with [Positioned].
  const AiGeneratedBadge.corner({
    super.key,
    this.label = 'AI',
    this.background,
    this.foreground = Colors.white,
  }) : compact = true;

  @override
  Widget build(BuildContext context) {
    final bg = background ?? Colors.black.withValues(alpha: 0.55);
    final double fontSize = compact ? 9 : 11;
    final double iconSize = compact ? 11 : 13;
    final EdgeInsets padding = compact
        ? const EdgeInsets.symmetric(horizontal: 6, vertical: 3)
        : const EdgeInsets.symmetric(horizontal: 10, vertical: 5);

    return Semantics(
      label: 'This content is generated by AI',
      child: Container(
        padding: padding,
        decoration: BoxDecoration(
          color: bg,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            color: foreground.withValues(alpha: 0.35),
            width: 0.8,
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.auto_awesome, size: iconSize, color: foreground),
            const SizedBox(width: 4),
            Text(
              label,
              style: TextStyle(
                color: foreground,
                fontSize: fontSize,
                fontWeight: FontWeight.w600,
                letterSpacing: 0.2,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
