import 'package:flutter/material.dart';

import '../theme/app_theme.dart';

/// The single in-app privacy policy. Kept substantively identical to the
/// canonical repo/web copy in `PRIVACY_POLICY.md`.
class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  /// Static effective date — keep in sync with PRIVACY_POLICY.md.
  static const String effectiveDate = 'May 19, 2026';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppSpacing.lg),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildSection(
              title: 'Privacy Policy',
              content: '''
Once Upon YOUR Child, powered by Story Weaver
Effective Date: $effectiveDate

Once Upon YOUR Child is committed to protecting the privacy and safety of children and families who use our storytelling platform. We believe that tools for children should be safe, transparent, and respectful of personal boundaries.
''',
            ),
            _buildSection(
              title: 'Information We Collect',
              content: '''
- Account information: parent/guardian email, username, basic profile, age range and preferences
- Usage data: story creation patterns, activity engagement, character progress, app usage statistics
- Story & feelings data: story goals and themes, milestone achievements, and any "big feelings" your child chooses to share — a short, optional piece of text used only to personalize a single story. We treat this emotional-state text as transient story-personalization input, not as a health record or a retained emotional profile of your child.
- Character & avatar data: character names and avatar choices. If a parent enables photo-based avatars, a photo used to create the child's character avatar (off by default, parental opt-in required; not stored on our servers)
''',
            ),
            _buildSection(
              title: 'How We Use Information',
              content: '''
- Personalize and generate stories, illustrations, and narration
- Provide age-appropriate content
- Track progress and growth
- Improve app functionality, quality, and safety
- Provide support if you contact us
- Process payments via Stripe (PCI compliant)
- Optional analytics to understand feature usage

We do NOT sell your data or use it for advertising.
''',
            ),
            _buildSection(
              title: 'AI-Generated Content',
              content: '''
Stories, illustrations, and character avatars in Once Upon YOUR Child are generated by artificial intelligence (AI). We use third-party AI providers (see Third-Party Services below) to create this content from the details your child provides — a character name, chosen themes, story goals, and any "big feelings" the child shares.

- Content is machine-generated. Stories and pictures are created automatically by AI — they are not written, drawn, or pre-approved by a human author or illustrator.
- AI output can be imperfect. AI is creative but not always accurate; it can occasionally produce content that is unexpected, wrong, or not quite right for your child. We apply safety filters, but no filter is perfect.
- It is for entertainment, not advice. Once Upon YOUR Child is a storytelling app. AI-generated stories are not reviewed by a teacher, doctor, or other professional, and are not a substitute for professional care.
- AI-generated stories and images carry a visible "Created with AI" label in the app.
- If you see AI content that seems wrong or unsafe, report it from the story screen ("Report this content") or email darcy@onceuponyourchild.app.

We encourage parents and guardians to review the stories their child creates.
''',
            ),
            _buildSection(
              title: 'Children\'s Privacy (COPPA)',
              content: '''
Once Upon YOUR Child is designed for children ages 3-17. We comply with the Children's Online Privacy Protection Act (COPPA) as enforced by the FTC:
- No personal data is collected from children under 13 without verifiable parental consent
- Parents/guardians must approve account creation for children under 13
- We do not sell or share children's data
- Parents can request deletion of their child's data at any time
- Age is collected to provide age-appropriate content and to determine COPPA applicability
''',
            ),
            _buildSection(
              title: 'Data Security',
              content: '''
- Data is encrypted in transit using TLS
- Data is stored on access-controlled servers
- Payment data and API keys are encrypted at rest
- Regular security reviews, access controls, and monitoring

We do not provide end-to-end encryption. Story content and account data are processed on our servers so the app can function.
''',
            ),
            _buildSection(
              title: 'Third-Party Services (Sub-processors)',
              content: '''
We share only the minimum data required for each service to function. Each provider's own privacy policy governs its processing.

- OpenAI — AI story-text and character-avatar generation. Receives a pseudonymized hero token (a non-identifying name used in place of the child's real name), story details, themes, any "big feelings" text the child shares, image/avatar prompts, and — only on the photo-avatar path — the child's photo.
- Cloudflare Workers AI — AI story-page illustrations (primary provider). Receives image prompts.
- Replicate — AI image and avatar generation (fallback). Receives image prompts, and on the photo-avatar path the child's photo.
- OpenRouter — routes AI image-generation requests (fallback). Receives image prompts, and on the photo-avatar path the child's photo.
- Google Gemini — a fallback provider for story illustrations (receives image prompts), and a voice-narration option (Gemini Flash TTS; see narration below).
- Voice narration (text-to-speech): the generated story text is sent to Microsoft (Azure AI Speech, the primary provider, and Edge TTS) and Google (Gemini Flash TTS). For ages 13+ only, premium/character voices may additionally use ElevenLabs (never for children under 13).
- Stripe — subscription and payment processing. Receives parent payment information; we never store full card details.
- Railway — cloud hosting and infrastructure (United States). Stores all app data: profiles, stories, preferences.
- Firebase / Google Analytics — app analytics. Receives anonymized usage events (consent-gated, off by default, not enabled for children under 13).
- Sentry — error monitoring. Receives crash and error diagnostics.
- Resend — sends COPPA parental-consent verification emails. Receives the parent/guardian email address.

The exact AI image provider used may vary by build and availability.

Photo avatars (optional): if you choose to create an avatar from a photo, the photo is sent to our servers and then to the active AI image provider solely to generate the cartoon avatar. It is not stored on our servers and is used for nothing else.
''',
            ),
            _buildSection(
              title: 'Data Retention',
              content: '''
- Active accounts: data retained while the account is active
- Inactive accounts: data deleted after 2 years of inactivity
- Legal requirements: some data may be retained to comply with laws
''',
            ),
            _buildSection(
              title: 'Your Rights & Parental Controls',
              content: '''
Parents and guardians have complete control over their child's data. You can:
- Access and update your data
- Request deletion of your child's data
- Request a copy of your child's data
- Opt out of analytics where supported
- Withdraw consent at any time

To delete your child's data: open the app → menu → Parent Controls → Data & Privacy → Delete All My Data. This permanently deletes your child's stories, characters and profile data and anonymizes your account so it can no longer be identified.

To exercise these rights, contact us at:
darcy@onceuponyourchild.app
''',
            ),
            _buildSection(
              title: 'Operator Identity & Contact',
              content: '''
This app is operated by:

- Operator (legal entity): Darcy VanPelt
- Postal address: 2816 Orchard Ave, Grand Junction, CO 81501
- Phone: 970-640-2011
- Email: darcy@onceuponyourchild.app

As required by COPPA, contact us using the details above to review, delete, or stop further collection of your child's information.
''',
            ),
            _buildSection(
              title: 'Not a Health or Therapeutic Product',
              content: '''
Once Upon YOUR Child is a storytelling and entertainment app with an emotional-wellbeing angle — it helps children explore feelings through personalized stories. It is not a therapeutic, clinical, or medical product, and it does not diagnose, treat, or provide care for any emotional or mental-health condition. The "big feelings" a child shares are used only to personalize a story; they are not retained as a health profile. Always consult a qualified professional for serious emotional or mental-health concerns.
''',
            ),
            _buildSection(
              title: 'Updates to This Policy',
              content: '''
Effective $effectiveDate. We may update this policy and will post changes here. We will notify users of material changes by email and in-app notification.
''',
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSection({required String title, required String content}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: AppSpacing.lg),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: AppSpacing.sm),
          Text(
            content.trim(),
            style: const TextStyle(
              fontSize: 16,
              height: 1.6,
            ),
          ),
        ],
      ),
    );
  }
}
